"""LicenseGate: loads and verifies an offline license token, and gates
not-yet-built enterprise features behind it.

The single-session CLI audit (solution_optimizer.cli) never imports or
calls anything in this module — the free path has no license check at
all. LicenseGate exists purely as scaffolding for the enterprise features
listed in BUILD-SCHEDULE.md (org dashboards, CI integration, trend
reports), none of which are implemented yet in this repo.

The public key embedded below (_PUBLIC_KEY_HEX) is this repo's real,
generated Ed25519 public key, produced by scripts/generate_dev_keypair.py
and committed here intentionally (public keys are meant to be public). The
matching private key lives only in the git-ignored dev_keys/ directory and
is never committed or pushed.
"""

from __future__ import annotations

import os

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from solution_optimizer.license.keys import (
    ExpiredLicenseError,
    InvalidLicenseError,
    verify_license,
)

# This repo's real embedded Ed25519 public key (hex-encoded raw 32-byte
# public key), generated by scripts/generate_dev_keypair.py.
_PUBLIC_KEY_HEX = "ec348361371b06ba365f724529c94f3d877c8c1f9575e97aa8d02d0774d0a2a0"

ENV_VAR_NAME = "CESO_LICENSE_KEY"

FREE_TIER = "free"

# Enterprise feature names. None of these are implemented in this repo yet
# -- see BUILD-SCHEDULE.md. Defining the constants now lets require_feature
# calls be added to future code without a magic-string typo risk.
ORG_DASHBOARD = "org_dashboard"
CI_INTEGRATION = "ci_integration"
TREND_REPORTS = "trend_reports"

_UPGRADE_CONTACT_PLACEHOLDER = "[placeholder: licensing contact email]"


class LicenseRequiredError(Exception):
    """Raised by LicenseGate.require_feature() when the current license
    (or lack thereof) does not grant the requested feature."""


def _load_public_key(public_key_hex: str) -> Ed25519PublicKey:
    raw = bytes.fromhex(public_key_hex)
    return Ed25519PublicKey.from_public_bytes(raw)


class LicenseGate:
    """Verifies a license token and exposes tier/feature-gating helpers.

    A LicenseGate with no valid token (missing, malformed, tampered,
    expired) always behaves as the free tier: `.tier == "free"` and
    `.has_feature(...)` is False for every feature name.
    """

    def __init__(
        self,
        token: str | None = None,
        public_key: Ed25519PublicKey | None = None,
        env_var: str = ENV_VAR_NAME,
    ) -> None:
        self._public_key = public_key or _load_public_key(_PUBLIC_KEY_HEX)
        self._token = token if token is not None else os.environ.get(env_var)
        self._payload: dict | None = None
        self._error: Exception | None = None

        if self._token:
            try:
                self._payload = verify_license(self._token, self._public_key)
            except (InvalidLicenseError, ExpiredLicenseError) as exc:
                self._payload = None
                self._error = exc

    @property
    def is_licensed(self) -> bool:
        """True only if a token was provided and verified successfully."""
        return self._payload is not None

    @property
    def tier(self) -> str:
        """"free" if no/invalid/expired license, else payload["tier"]
        (falling back to "free" if the payload has no explicit tier)."""
        if self._payload is None:
            return FREE_TIER
        return self._payload.get("tier", FREE_TIER)

    @property
    def verification_error(self) -> Exception | None:
        """The exception raised while verifying the token, if any (useful
        for diagnostics; None if there was no token or it verified fine)."""
        return self._error

    def features(self) -> list[str]:
        """The list of feature names granted by the current license.
        Empty for the free tier."""
        if self._payload is None:
            return []
        raw = self._payload.get("features", [])
        if not isinstance(raw, list):
            return []
        return list(raw)

    def has_feature(self, name: str) -> bool:
        """True only if the verified license payload explicitly grants
        `name` in its "features" list. Always False on the free tier."""
        return name in self.features()

    def require_feature(self, name: str) -> None:
        """Raise LicenseRequiredError if `name` is not granted by the
        current license. No-op (returns None) if it is granted."""
        if self.has_feature(name):
            return
        raise LicenseRequiredError(
            f"This feature ({name!r}) requires a license that grants it, but the "
            f"current tier is {self.tier!r}. Contact {_UPGRADE_CONTACT_PLACEHOLDER} "
            "to upgrade."
        )
